### ISSUE TITLE
panic in xterm on linux

### ISSUE THREAD

**Issue by madelynnblue** [knz/go-libedit#20]
```
SIGTRAP: trace trap PC=0x7dc8a2 m=2 sigcode=128

goroutine 0 [idle]:
runtime.abort()
        /usr/local/go/src/runtime/asm_amd64.s:859 +0x2
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:416 +0x25

goroutine 1 [syscall]:
github.com/knz/go-libedit/unix._C2func_go_libedit_gets(0x7fd972547600, 0x7fd940c0d000, 0x0, 0x0, 0xc000ca5bd8, 0xc000ca5bdc, 0x1, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:194 +0x56
github.com/knz/go-libedit/unix.EditLine.GetLine.func1(0xc00039c380, 0xc000ca5bd8, 0xc000ca5bdc, 0x46, 0x7fd940c0d000, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:281 +0xe3
github.com/knz/go-libedit/unix.EditLine.GetLine(0x0, 0x46, 0xb, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:281 +0xaa
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doReadLine(0xc000a30200, 0x6, 0x5)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:873 +0x603
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc00081d180, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1282 +0xeb
github.com/cockroachdb/cockroach/pkg/cli.runClient(0x77d8dc0, 0xc00081d180, 0x1, 0xc00081d180)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1492 +0x78
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x77d8dc0, 0xc000511920, 0x0, 0x2, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1479 +0xc4
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x77d8dc0, 0xc000511920, 0x0, 0x2, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:188 +0x79
github.com/spf13/cobra.(*Command).execute(0x77d8dc0, 0xc000511900, 0x2, 0x2, 0x77d8dc0, 0xc000511900)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x77d0940, 0xc000076180, 0xc0009cd82a, 0x3)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:223
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:67 +0x270
main.main()
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short/main.go:26 +0x20
```

**Comment by madelynnblue** [comment]
Afterward I can't use up arrow or see any typed characters in my terminal. However if I type stuff then hit enter it'll show the command. Could have something to do with resizing or `scrollTtyOutput: false` in .Xresources.

**Comment by knz** [comment]
I think this may be fixed by #25. Feel free to close if confirmed. I wasn't able to repro your issue.
